/**
 * Fincava Universal Provenance Model
 *
 * Every AI-generated output in this system operates within a declared evidence tier.
 * Prompts reference PROVENANCE_PREAMBLE by name and inject it verbatim.
 * Do not paraphrase or abbreviate — consistency across all prompts is the point.
 *
 * Tier order (lowest → highest confidence):
 *   AI_INFERRED → SELF_REPORTED → UPLOADED_UNREVIEWED → ADMIN_REVIEWED → VERIFIED_EXTERNAL
 */

export const PROVENANCE_TIERS = {
  SELF_REPORTED:        "self-reported by supplier (not independently verified)",
  AI_INFERRED:          "AI-inferred from available signals (treat as preliminary draft only)",
  UPLOADED_UNREVIEWED:  "document uploaded — awaiting admin review",
  ADMIN_REVIEWED:       "reviewed and approved by a Fincava administrator",
  VERIFIED_EXTERNAL:    "confirmed by an independent external body",
} as const;

export type ProvenanceTier = keyof typeof PROVENANCE_TIERS;

/**
 * Shared preamble injected into all Tier 3–5 prompts (scoring, matching, summaries).
 * Paste with ${PROVENANCE_PREAMBLE} inside a template literal.
 */
export const PROVENANCE_PREAMBLE = `
EVIDENCE TIERS — apply to every claim in your output:
- SELF_REPORTED: stated by the supplier on their onboarding form. Never treat as externally verified.
- AI_INFERRED: generated by AI from available signals. Always treat as preliminary and potentially incorrect.
- UPLOADED_UNREVIEWED: a document exists in the system but has not been examined by a Fincava administrator.
- ADMIN_REVIEWED: a Fincava administrator has examined and approved the item.
- VERIFIED_EXTERNAL: confirmed by an independent external body (only use when the input data explicitly states this).

Rules:
1. Your output inherits the lowest evidence tier present in your inputs.
2. SELF_REPORTED ≠ true. UPLOADED_UNREVIEWED ≠ valid. AI_INFERRED ≠ reliable.
3. Scoring, pathways, and recommendations derived from SELF_REPORTED or AI_INFERRED inputs
   must be labelled as PRELIMINARY ESTIMATES — not assessments, certifications, or decisions.
4. Only ADMIN_REVIEWED or VERIFIED_EXTERNAL inputs can support a definitive claim.
`.trim();
