import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import storageRouter from "./storage";
import productsRouter from "./products";
import suppliersRouter from "./suppliers";
import inquiriesRouter from "./inquiries";
import ordersRouter from "./orders";
import statsRouter from "./stats";
import reviewsRouter from "./reviews";
import messagesRouter from "./messages";
import usersRouter from "./users";
import rfqsRouter from "./rfqs";
import shipmentsRouter from "./shipments";
import analyticsRouter from "./analytics";
import storiesRouter from "./stories";
import financingRouter from "./financing";
import adminRouter from "./admin";
import officersRouter from "./officers";
import buyersRouter from "./buyers";
import aiAssistantRouter from "./ai-assistant";
import publicContentRouter from "./public-content";
import adminComplianceQueueRouter from "./adminComplianceQueue";
import officerComplianceRouter from "./officerCompliance";
import complianceWidgetRouter from "./complianceWidget";
import complianceEvaluatorRouter from "./complianceEvaluator";
import adminManagedCasesRouter from "./adminManagedCases";
import supplierExportModeRouter from "./supplierExportMode";
import reviewSuggestionRouter from "./reviewSuggestion";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(storageRouter);
router.use(productsRouter);
router.use(suppliersRouter);
router.use(inquiriesRouter);
router.use(ordersRouter);
router.use(statsRouter);
router.use(reviewsRouter);
router.use(messagesRouter);
router.use(usersRouter);
router.use(rfqsRouter);
router.use(shipmentsRouter);
router.use(analyticsRouter);
router.use(storiesRouter);
router.use(financingRouter);
router.use(adminRouter);
router.use(officersRouter);
router.use(buyersRouter);
router.use(aiAssistantRouter);
router.use(publicContentRouter);
router.use(adminComplianceQueueRouter);
router.use(officerComplianceRouter);
router.use(complianceWidgetRouter);
router.use(complianceEvaluatorRouter);
router.use(adminManagedCasesRouter);
router.use(supplierExportModeRouter);
router.use(reviewSuggestionRouter);

export default router;
